<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCategoriesByParent(Category $parent = null)
	{
		$qb = $this->createQueryBuilder('c')
			->orderBy('c.name', 'ASC');

		if ($parent === null) {
			$qb->andWhere('c.parent IS NULL');
		} else {
			$qb->andWhere('c.parent = :parent')
				->setParameter('parent', $parent->getId());
		}

		return $qb->getQuery()->getResult();
	}
}
