<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

/**
 * ReviewRepository
 *@ParamConverter("product", class="AppBundle\Entity\Product", options={"mapping": {"product": "id"}})
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllComments(Product $product) {
		return $this->createQueryBuilder('c')
			->where('c.product = :product')
			->setParameter('product', $product)
			->addOrderBy('c.dateAdded', 'DESC')
			->getQuery()
			->getResult();
	}
}
